### ISSUE TITLE
releasing v0.3.0 -- checklist

### ISSUE THREAD

**Issue by wyli** [Project-MONAI/MONAI#1077]
Release a candidate version
- [x] Tag and release PYPI version [X.Y.Z]rc[K] following the contributing guide.
- [x] Make sure all CI pipelines pass.
- [x] Check the PyPI page
- [x] Test pip install monai==[X.Y.Z]rc[K] and run a few MONAI modules locally
- [x] Test all installation commands mentioned in the installation guide and the primary README.

Quality assurance for the relevant repos
The new PyPI release candidate should be checked against all the relevant repositories under Project-MONAI, for example, the tutorials repo
- [x] Manually run all Jupyter notebooks, replace pip install monai with pip install monai==[X.Y.Z]rc[K]. (https://github.com/Project-MONAI/tutorials/issues/33)

Prepare documentation
- [x] Draft a release note on GitHub.
- [x] Draft a release note with a pull request to modify the CHANGELOG.
- [x] Create a pull request to highlight the features of the upcoming release, for example, in docs/source/highlights.md.
- [x] Create a pull request to update the primary README.md.
- [x] Update the monai.io website (https://github.com/Project-MONAI/project-monai.github.io).
- [x] Check all the URLs in https://monai.io and https://docs.monai.io.

Release a milestone version
- [x] Tag and release PyPI version [X.Y.Z] following the contributing guide.
- [x] Publish the release note on GitHub.
- [x] Revisit the GitHub project tab Update https://github.com/Project-MONAI/MONAI/projects.

**Comment by Nic-Ma** [comment]
Hi @wyli ,

I already tested all the notebooks and examples except the Horovod example, and submitted PR to fix issues:
https://github.com/Project-MONAI/tutorials/pull/40
Could you please help tag for v0.3, then delete the `install monai latest code, delete when v0.3 released` cell in all the new notebooks?

Thanks.

**Comment by wyli** [comment]
> Hi @wyli ,
> 
> I already tested all the notebooks and examples except the Horovod example, and submitted PR to fix issues:
> [Project-MONAI/tutorials#40](https://github.com/Project-MONAI/tutorials/pull/40)
> Could you please help tag for v0.3, then delete the `install monai latest code, delete when v0.3 released` cell in all the new notebooks?
> 
> Thanks.

sure I'll do that. also I think we should remove the `-U` option in tutorial `pip install`, because it seems there's no need to enforce the latest pytorch/numpy...
