### ISSUE TITLE
releasing v0.8.1 -- checklist

### ISSUE THREAD

**Issue by wyli** [Project-MONAI/MONAI#3479]
Patch release -- Tentative date: ~Jan~ Feb

Release a candidate version
- [x] Tag and release PYPI version [X.Y.Z]rc[K] following the contributing guide.
- [x] Make sure all CI pipelines pass.
- [x] Check the PyPI page
- [x] Test pip install monai==[X.Y.Z]rc[K] and run a few MONAI modules locally
- [x] Test all installation commands mentioned in the installation guide and the primary README.
- [x] remove any promised deprecated functionality

Quality assurance for the relevant repos
The new PyPI release candidate should be checked against all the relevant repositories under Project-MONAI, for example, the tutorials repo
- [x] Manually run all Jupyter notebooks, replace pip install monai with pip install monai==[X.Y.Z]rc[K].

Prepare documentation
- [x] Draft a release note on GitHub. (including details about the breaking changes)
- [x] Draft a release note with a pull request to modify the CHANGELOG.
- [x] Check all the URLs in https://monai.io 
- [x] Check all the URLs in https://docs.monai.io.
 
Release a milestone version
- [x] Tag and release PyPI version [X.Y.Z] following the contributing guide.
- [x] Publish the release note on GitHub.
- [x] Release the conda-forge version https://github.com/conda-forge/monai-feedstock (https://github.com/conda-forge/monai-feedstock/pull/2)

**Comment by wyli** [comment]
V0.8.1 will have minor code&doc quality/usability improvements based on various user feedback.

**Comment by wyli** [comment]
The release candidates are made available https://pypi.org/project/monai/#history, release note: https://github.com/Project-MONAI/MONAI/pull/3489 please help to test it!
