### ISSUE TITLE
releasing v0.9.0 -- checklist

### ISSUE THREAD

**Issue by wyli** [Project-MONAI/MONAI#4323]
Tentative date: 15th June

Release a candidate version

- [ ] Tag and release PYPI version [X.Y.Z]rc[K] following the contributing guide.
- [ ] Make sure all CI pipelines pass.
- [ ] Check the PyPI page
- [ ] Test pip install monai==[X.Y.Z]rc[K] and run a few MONAI modules locally
- [ ] Test all installation commands mentioned in the installation guide and the primary README.
- [ ] remove any promised deprecated functionality

Quality assurance for the relevant repos

- [ ] The new PyPI release candidate should be checked against the tutorials repo
- [ ] Manually run all Jupyter notebooks, replace pip install monai with pip install monai==[X.Y.Z]rc[K].

Prepare documentation

- [ ] Draft a release note on GitHub. (including details about the breaking changes)
- [ ] Draft a release note with a pull request to modify the CHANGELOG.
- [ ] Check all the URLs in https://monai.io/
- [ ] Check all the URLs in https://docs.monai.io/.

Release a milestone version

- [ ] Tag and release PyPI version [X.Y.Z] following the contributing guide.
- [ ] Publish the release note on GitHub.
- [ ] Release the conda-forge version https://github.com/conda-forge/monai-feedstock
- [ ] Review citation item https://zenodo.org/record/4323059
- [ ] Update the weekly-preview tagging https://github.com/Project-MONAI/MONAI/blob/46f3074c7297429fc810a901c212678ebd3b0afa/.github/workflows/weekly-preview.yml#L36

**Comment by Constantin-Jehn** [comment]
Hello,

I downloaded the new release via conda-forge and noticed that pytorch is downgraded to a cpu-only version.
I (and assume many others) would prefer keeping the cuda version of pytorch.
<img width="838" alt="grafik" src="https://user-images.githubusercontent.com/66247479/173776922-6f293821-28ae-4fae-a643-8c496c4b22d6.png">

Best,
Constantin

**Comment by wyli** [comment]
I haven't tested it, but I suspect you should install pytorch first, as suggested here:
![Screenshot 2022-06-15 at 09 22 37](https://user-images.githubusercontent.com/831580/173779506-ce3eb1bd-6b03-4e5b-bf4b-ca44b8fc85f0.png)
