### ISSUE TITLE
releasing v0.9.1 -- checklist

### ISSUE THREAD

**Issue by wyli** [Project-MONAI/MONAI#4632]
Tentative date: 18th July
MetaTensor dev guide: https://colab.research.google.com/drive/1T4iAys-cC2qL80oJkIbAXAPlWNPwp4H7

Release a candidate version

- [x] Tag and release PYPI version [X.Y.Z]rc[K] following the contributing guide.
- [x] Make sure all CI pipelines pass.
- [x] Check the PyPI page
- [x] Test pip install monai==[X.Y.Z]rc[K] and run a few MONAI modules locally
- [x] Test all installation commands mentioned in the installation guide and the primary README.
- [x] remove any promised deprecated functionality

Quality assurance for the relevant repos

- [x] The new PyPI release candidate should be checked against the tutorials repo
- [x] Run all Jupyter notebooks, replace pip install monai with pip install monai==[X.Y.Z]rc[K] (remaining items tracked here https://github.com/Project-MONAI/tutorials/issues/819).

Prepare documentation

- [x] Draft a release note on GitHub. (including details about the breaking changes)
- [x] Draft a release note with a pull request to modify the CHANGELOG.
- [x] Check all the URLs in https://monai.io/
- [x] Check all the URLs in https://docs.monai.io/

Release a milestone version

- [x] Tag and release PyPI version [X.Y.Z] following the contributing guide.
- [x] Publish the release note on GitHub.
- [x] Release the conda-forge version https://github.com/conda-forge/monai-feedstock
- [x] Review citation item https://zenodo.org/record/4323059 (https://github.com/Project-MONAI/MONAI/pull/4762)
