### ISSUE TITLE
Add modules and pipeline for Auto3D

### ISSUE THREAD

**Issue by mingxin-zheng** [Project-MONAI/MONAI#4743]
**Is your feature request related to a problem? Please describe.**
Motivation: Automating selection of deep neural network training pipelines with the following specific requirements:
- Re-implement AutoML modules and pipeline under monai/apps/automl;
- Implement module demo in tutorials;
- Use monai.bundle to provide users with easy-to-read Python scripts and options to call the functions in bash and native python.

**Describe the solution you'd like**
Progress: https://github.com/Project-MONAI/MONAI/pull/4765
**Usage Proposal**
https://github.com/mingxin-zheng/tutorials/blob/auto3d-1.0/auto3d/README.md

**Tasks**
- [x] Encapsulate data analysis module in a Python class. The module shall find data and label from user inputs and generate a summary (dictionary) of data stats. The summary includes
	- file names, list, number of files;
	- dataset summary (basic information, image dimensions, number of classes, etc.);
	- individual data information (spacing, image size, number and size of the regions, etc.).
- [ ] Encapsulate the configuration module in a Python class. The module shall use the data stats dict/file to generate task related directory and Python code scripts (train.py/main.py/infer.py) for each specific algorithm
	- Implement an algorithm selection class to select algorithms for next step. The class is aimed to enable future smart algorithm selection;
	- It should use the monai.bundle to provide a native Python programming experience to the user
	- Note: for the current 1.0 release aim, only one network will be implemented
- [ ] Encapsulate the multi-fold training processes in a class, or implement them in the pipeline class (see below)
- [ ] Encapsulate the ensemble module in a class
- [ ] Develop a new pipeline class to run all or selective modules sequentially, and provide results (segmentation predictions) to the user
	- Develop a pipeline for users to directly adopt trained/searched models for testing purpose (model infernece and ensemble) with their own datasets;
- [ ] Python scripts in tutorials to demonstrate each of the modules and the pipeline class.

**Comment by mingxin-zheng** [comment]
Closing this issue because Auto3Dseg was successfully merged into the dev branch and released in MONAI 1.0 .
