### ISSUE TITLE
Instrument code with typehints

### ISSUE THREAD

**Issue by hjmjohnson** [Project-MONAI/MONAI#476]
**Is your feature request related to a problem? Please describe.**

We believe statically typing what are essentially fully dynamic languages will give MONAI code stability and improve developer productivity.

Attempt to use modern python preferred pep 484 support.
This allows advanced linters to more aggressively perform static
validation checking.
    
Using typehints as annotations allow for a more DRY (Do not repeat
yourself) implementation that supports various type checking linters and
documentation support.
    
Some pytype warnings will require more extensive corrections to fully
resolve them.  These few cases are suppressed in the interest of
allowing more static checks without imposing a huge burden at the moment.

**Describe the solution you'd like**
Instrument code with type hint static checkers and PEP484 type hints.

# This task will not be complete until 

- [x] enable mypy (Still currently the gold standard) completed in #496,  
- [x] enable flake8-mypy (possibly with limitations as it is pretty unstable and most unmaintained).
- [x] enable pytype (suggested replacement to flake8-mypy) (#492 - DONE)
- [x]  mute/fix existing warnings by, for example, setting the config exclude=*.py (#483, #480)
- [x]  set up CI pipeline so that we can verify every PR in the future (#483)
- [x] setup an initial config of the relevant tools (#477 - DONE)
- [x]  incremental PRs to enable submodule checks, for example, change the config from exclude=*.py to exclude=monai/transforms/*.py (#477 - DONE )(#479 - DONE) (#481 - Replaced)
- [ ] incremental PRs to add new type hints to the existing modules (#482 - Rejected) (TBD)(TBD)(TBD)(TBD)
- [x] Add temporary `#type: ignore` and `pytype: disable=?????` suppressions so that big-ticket changes can be cleanly addressed as a pirority (#496 -DONE)
- [ ] Find all temporary `# type: ignore` items and resolve the temporary suppression with proper type hinting.
- [X] review setup.cfg and remove temporary suppression of typehint warnings (#499 -Done)  Mypy and flake8 options appear to be in good shape as well.  

the last two steps could happen in parallel

**Comment by hjmjohnson** [comment]
The plan is to make MONAI code base pass tests with pytype static analysis, and mypy static analysis tools, along with flake8-mypy  integrations.

The MONAI package should be sufficiently instrumented with type hints so that all the docstring types used to indicate expected types to developers can be statically checked and validated by the above-mentioned tools.

Eventually, the entire MONAI toolkit should be compatible with type hinting for all public-facing interfaces.

**Comment by wyli** [comment]
thanks, the flake8-mypy CI tests currently works fine
for a concrete plan to enable mypy and pytype:
- [x] setup an initial config of the relevant tools (https://github.com/Project-MONAI/MONAI/pull/477)
- [ ] mute/fix existing warnings by, for example, setting the config `exclude=*.py` (https://github.com/Project-MONAI/MONAI/pull/483, https://github.com/Project-MONAI/MONAI/pull/480)
- [ ] set up CI pipeline so that we can verify every PR in the future (https://github.com/Project-MONAI/MONAI/pull/483)
- [ ] incremental PRs to enable submodule checks, for example, change the config from `exclude=*.py` to `exclude=monai/transforms/*.py` (https://github.com/Project-MONAI/MONAI/pull/481)
- [ ] incremental PRs to add new type hints to the existing modules (https://github.com/Project-MONAI/MONAI/pull/482)

**Comment by wyli** [comment]
thanks for pushing this forward @hjmjohnson, we also need 
- [ ] some simple instructions such as https://github.com/Project-MONAI/MONAI/blob/master/CONTRIBUTING.md#linting-and-code-style-testing to run local tests before PR

**Comment by hjmjohnson** [comment]
> thanks for pushing this forward @hjmjohnson, we also need
> 
> * [ ]  some simple instructions such as https://github.com/Project-MONAI/MONAI/blob/master/CONTRIBUTING.md#linting-and-code-style-testing to run local tests before PR

@wyli We have some of that locally, but as we figure out how to use pytype, mypy, and other validators (i.e. we spend a lot of time with pyre, but it is really hard to install, and does not seem to produce meaningfully useful failures at this point in our type hinting journey).
 
@crtrentz @benjamin-gorman I know you have been working notes for how to use, configure, and resolve problems identified with pytype and mypy. Please modify the recommended CONTRIBUTING.md file with your notes as an independant PR on the master branch.

**Comment by wyli** [comment]
Major APIs and docstrings are now revised to fully support typehints. closing this ticket -- please create new specific tickets to address any further typehint related issues.
