### ISSUE TITLE
releasing v1.0 -- checklist

### ISSUE THREAD

**Issue by wyli** [Project-MONAI/MONAI#5090]
# Milestone Release Checklist (for the maintainers)
Tentative date: 16th Sept

## Release candidate versions
- [x] Tag and release PYPI version [X.Y.Z]rc[K] following [the contributing guide](https://github.com/Project-MONAI/MONAI/blob/master/CONTRIBUTING.md#release-a-new-version).
- [x] Make sure all CI pipelines pass.

## Verify the new release candidates
- [x] Check [the PyPI page](https://pypi.org/project/monai/0.2.0/) 
- [x] Test `pip install monai==[X.Y.Z]rc[K]` and run a few MONAI modules locally
- [x] Test all installation commands mentioned in [the installation guide](https://docs.monai.io/en/latest/installation.html) and [the primary README](https://github.com/Project-MONAI/MONAI/blob/master/README.md).

## Quality assurance for the relevant repos
The new PyPI release candidate should be checked against all the relevant repositories under [`Project-MONAI`](https://github.com/Project-MONAI), for example, [the tutorials repo](https://github.com/Project-MONAI/tutorials):
- [x] Run all Jupyter notebooks, replace `pip install monai` with `pip install monai==[X.Y.Z]rc[K]`.
  - File new tickets and create new pull requests to address any technical issues.
- [x] Release a new candidate after addressing all the issues.

## Prepare documentation
- [x] Draft a release note [on GitHub](https://github.com/Project-MONAI/MONAI/releases).
- [x] Draft a release note with a pull request to modify [the CHANGELOG](https://github.com/Project-MONAI/MONAI/blob/master/CHANGELOG.md). (https://github.com/Project-MONAI/MONAI/pull/5139)
- [x] Create a pull request to highlight the features of the upcoming release, for example, in [`docs/source/highlights.md`](https://github.com/Project-MONAI/MONAI/blob/master/docs/source/highlights.md). (https://github.com/Project-MONAI/MONAI/pull/5128)
- [x] Create a pull request to update [the primary README.md](https://github.com/Project-MONAI/MONAI/blob/master/README.md).(https://github.com/Project-MONAI/MONAI/pull/5128)
- [x] Check all the URLs in `https://monai.io` 
- [x] Check all the URLs in `https://docs.monai.io`.

## Release a milestone version
- [x] Tag and release PyPI version [X.Y.Z] following [the contributing guide](https://github.com/Project-MONAI/MONAI/blob/master/CONTRIBUTING.md#release-a-new-version).
- [x] Check the dockerhub auto-build by running `docker pull projectmonai/monai:X.Y.Z` and `docker run ...`
- [x] Check readme frontpage on dockerhub, pypi
- [x] Update https://github.com/Project-MONAI/MONAI/blob/dev/CITATION.cff
- [x] Publish the release note [on GitHub](https://github.com/Project-MONAI/MONAI/releases).
- [x] Update the weekly-preview tagging https://github.com/Project-MONAI/MONAI/blob/master/.github/workflows/weekly-preview.yml#L32 (https://github.com/Project-MONAI/MONAI/pull/5170)
- [x] Release the corresponding conda-forge version https://github.com/conda-forge/monai-feedstock

## Revisit the GitHub project tab
- [ ] Update https://github.com/Project-MONAI/MONAI/projects.

## Review the deprecated APIs
- [x] remove any promised deprecated functionality
