### ISSUE TITLE
releasing v1.0.1 -- checklist

### ISSUE THREAD

**Issue by wyli** [Project-MONAI/MONAI#5284]
Tentative date: 17th October
minor bug fix release

Release a candidate version

- [x] Tag and release PYPI version [X.Y.Z]rc[K] following the contributing guide.
- [x] Make sure all CI pipelines pass.
- [x] Check the PyPI page
- [x] Test pip install monai==[X.Y.Z]rc[K] and run a few MONAI modules locally
- [x] Test all installation commands mentioned in the installation guide and the primary README.

Quality assurance for the relevant repos

- [x] The new PyPI release candidate should be checked against the tutorials repo
- [x] Run all Jupyter notebooks, replace pip install monai with pip install monai==[X.Y.Z]rc[K]

Prepare documentation

- [x] Draft a release note on GitHub. (including details about the breaking changes)
- [x] Draft a release note with a pull request to modify the CHANGELOG.
- [x] Check all the URLs in https://docs.monai.io/

Release a hotfix version

- [x] Tag and release PyPI version [X.Y.Z] following the contributing guide.
- [x] Publish the release note on GitHub.
- [x] Release the conda-forge version https://github.com/conda-forge/monai-feedstock

**Comment by wyli** [comment]
v1.0.1 hotfix release is now available, highly recommended for all v1.0.0 users.
