### ISSUE TITLE
image data reader and LoadImage transform refactoring

### ISSUE THREAD

**Issue by wyli** [Project-MONAI/MONAI#909]
This is a follow-up of #856 to track the progress of a preliminary IO refactoring.

**Goal**

The main goal of this ticket is to create a file format agnostic wrapper for the image inputs (`LoadImage` and `LoadImaged`).
A typical use case (enhancing the current [`NiftiDataset`](https://github.com/Project-MONAI/MONAI/blob/6a6f52f5f80e5c706f1f0976aa76b56af488d119/monai/data/nifti_reader.py#L21)) is:
```python
train_ds = ImageDataset(images, segs, transform=train_imtrans, seg_transform=train_segtrans)
```
where `images` and `segs` are filenames, `ImageDataset` internally invokes `LoadImage`.

Or using a generic monai Dataset API, specify the first component of `train_imtrans` as a `LoadImage` transform that extracts data array and meta data from the file.

More specifically:

**Reader** （file format-specific component)

1. `[format]reader` are themselves monai data components (users can use the readers without going through the `LoadImage` logic), they call external package APIs
2. `[format]reader` share the same superclass `ImageReader` interface (for handling physical/voxel resolution, orientation...)
```py
class ImageReader:
    def get_data(self, ...):
        # return the data in the designated resolution, orientation, 
        # image channel selector, the relevant coordinates, datatype
    
    def read(self, ...):
        # create an IO object instance or a set of instances
```
3. users can make customized `MyReader` by implementing the `ImageReader` interface
4. the customized `MyReader` could be registered with the `LoadImage` factory
```python
@register_reader(requires='my_external_library')
class MyReader(ImageReader):
    ...
```

**LoadImage**（file format agnostic component)

1. `LoadImage` is a monai transform
2. `LoadImaged` should return the same underlying data representation dictionary regardless of the image format.
3. `LoadImage` may choose a suitable `[format]reader` dynamically at runtime based on the following rules (ordered from high to low priority):
  - user's selection of a specific reader, such as `LoadImage(reader='ITkReader')`
  - try any user-registered readers
  - try resources map based on a global property file and filename extensions:
  ```
  MONAI.IO
  {
      FOO LoadFOO
      PNG  ITK/5.1/LoadITK
      TIFF,TIF  ITK/5.1/LoadITK
      * ITK/5.1/LoadITK
  }
  ```
  - fails early and preserves detailed error messages

**additional requirements**
- should be able to specify versions of external reader to ensure reproducibility
- need to have consistent coordinate systems, resolution conventions

**tasks**
- [x] implement interface `ImageReader`, factory (transforms) `LoadImage` `LoadImaged`
- [x] implement ITKReader, NibabelReader, NumpyReader, PILReader?
- [x] `LoadImage` selecting readers according to the preference list
- [x] new interfaces tutorial https://github.com/Project-MONAI/Tutorials/pull/19
- [x] deprecate `NiftiDataset`, add `ImageDataset`
- [x] deprecate `LoadNifti`, `LoadPNG`, `LoadNumpy`, `LoadDatad`
- [x] revise/check all examples demos

**Comment by wyli** [comment]
thanks for the discussion @Nic-Ma  let's use this ticket to raise any detailed technical issues

**Comment by Nic-Ma** [comment]
Mark: completed 2 tasks in the list, will work on `NumpyReader`, `PILReader` in the next PR.
Thanks.

**Comment by wyli** [comment]
before deprecating the previous loaders, would be very helpful to have a new tutorial to demonstrate the new interfaces, what do you think @Nic-Ma?

**Comment by Nic-Ma** [comment]
Hi @wyli ,

Sounds good a plan.
Please submit a ticket and assign it to me.

Thanks.

**Comment by wyli** [comment]
this ticket is currently blocked at https://github.com/InsightSoftwareConsortium/ITK/issues/2003 because the default is 
https://github.com/Project-MONAI/MONAI/blob/99f7a439020bac0c70de1a5096bb24aceeaf4ae5/monai/transforms/io/array.py#L62-L63

**Comment by Nic-Ma** [comment]
Here is the plan for this ticket in v0.4 development:
1. Change the default reader of `LoadImage` to Nibabel.
2. Add string support for the reader parameter.
3. Update all the examples and tutorials to use `LoadImage` transform.

Thanks.

**Comment by Nic-Ma** [comment]
Will deprecate `NiftiDataset`, add `ImageDataset` in another separate PR later.
Thanks.
