### ISSUE TITLE
Meta Learning Module

### ISSUE THREAD

**Issue by Vector-Wang** [Project-MONAI/MONAI#924]
## Introduction
Meta Learning is an emerging research direction of machine learning theory. [Learning to Reweight Examples for Robust Deep Learning](https://arxiv.org/abs/1803.09050) describled a reweight method based on meta learning. It's useful for corrupted and imblanced labels. [Here](https://github.com/danieltan07/learning-to-reweight-examples) is an unoffical pytorch implementation.  There are lots of works applied meta learning to solve real problems, such as [Meta-Weight-Net: Learning an Explicit Mapping For Sample Weighting](https://arxiv.org/abs/1902.07379)(NeurIPS2019) and [Meta Corrupted Pixels Mining for Medical Image Segmentation](https://arxiv.org/abs/2007.03538)(MICCAI2020).

## Solution
It's not complicated, only add some meta modules and add several codes in network.layers.factories. 
I've implemented a version of this feature. If accepted, I will submit the PR.

**Comment by wyli** [comment]
thanks @Vector-Wang. this looks very interesting, would you be happy to create a research prototype first? 

ideally the PR would
- [ ] have a readme file (with reference of the original publication)
- [ ] depend on a publicly-available small dataset (or even synthetic data) so that we can quickly download the data and run/verify the research prototype
- [ ] simple scripts to show the key features

there are a few examples in  https://github.com/Project-MONAI/MONAI/tree/master/research

as a first step, the PR shouldn't change the core codebase in https://github.com/Project-MONAI/MONAI/tree/master/monai unless it's 100% necessary. we could take another iteration to identify generic interfaces from the prototype and merge the relevant new features into the core.

**Comment by rawwar** [comment]
@wyli , I want to give this a try. But, I don't see the research folder in the master branch. Where do i put the code?

**Comment by wyli** [comment]
> @wyli , I want to give this a try. But, I don't see the research folder in the master branch. Where do i put the code?

sure please go ahead, the folder now becomes a repo https://github.com/Project-MONAI/research-contributions

**Comment by vikashg** [comment]
closing because of inactivity
